blank_issues_enabled: false
contact_links:
  - name: ISLE Project Management Office
    url: pmo@isle.plus
    about: Please report project management related concerns here.
  - name: ISLE Security Office
    url: https://secmon.isle.plus
    about: Please report security vulnerabilities here.
