blank_issues_enabled: false
# GitHub doesn't currently support email addresses
contact_links:
  - name: ISLE Security Office
    url: mailto:secmon@isle.plus
    mail: secmon@isle.plus
    email: secmon@isle.plus
    about: Please report security vulnerabilities here.
